# Generated by Django 4.2.7 on 2025-12-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdata',
            name='recommendations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
