# Generated by Django 5.2.7 on 2025-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_iotdata_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key (e.g. cpu_threshold)', max_length=100, unique=True)),
                ('value', models.CharField(help_text='Setting value', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting does')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
