# Generated by Django 5.2.7 on 2025-12-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='CSS color value (e.g. rgba(...))', max_length=50)),
                ('min_percentage', models.IntegerField(help_text='Minimum score percentage for this mood')),
            ],
            options={
                'ordering': ['min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question text')),
                ('options', models.JSONField(help_text='List of 4 answer options')),
                ('correct_answer', models.IntegerField(help_text='Index of correct answer (0-3)')),
                ('reactions_correct', models.JSONField(default=list, help_text='List of reactions to show on correct answer')),
                ('reactions_wrong', models.JSONField(default=list, help_text='List of reactions to show on wrong answer')),
                ('fun_fact', models.TextField(blank=True, help_text='Fun fact displayed after answering')),
                ('order', models.IntegerField(default=0, help_text='Display order of the question')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResultMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('emoji', models.CharField(max_length=10)),
                ('color_class', models.CharField(help_text='Bootstrap color class (success, warning, etc.)', max_length=20)),
                ('badge_text', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Number of correct answers')),
                ('total_questions', models.IntegerField(help_text='Total questions answered')),
                ('percentage', models.FloatField(help_text='Score as percentage')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
